services:
  api.bruno-guimaraes.com:
    image: api.bruno-guimaraes.com:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RESEND_API_KEY=${RESEND_API_KEY}
      - AUTH_TOKEN=${AUTH_TOKEN}
      - EMAIL_ADMIN=${EMAIL_ADMIN}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - GO_ENV=${GO_ENV}
    restart: unless-stopped
    container_name: api.bruno-guimaraes.com