version: "3.8"

services:
  email-service:
    image: email-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RESEND_API_KEY=${RESEND_API_KEY}
      - AUTH_TOKEN=${AUTH_TOKEN}
    restart: unless-stopped
    container_name: email-service