name: CI/CD to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and tag the Docker image
      - name: Build Docker Image
        run: |
          docker build -t email-service:latest -f Dockerfile .

      # Deploy to EC2 via SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to the project directory
            cd ~/email-service

            # Pull the latest code
            git pull origin main

            # Set environment variables
            export RESEND_API_KEY="${{ secrets.RESEND_API_KEY }}"
            export AUTH_TOKEN="${{ secrets.AUTH_TOKEN }}"

            # Stop and remove existing containers
            docker-compose down

            # Build and start the new container
            docker-compose up -d --build